### ISSUE TITLE
Getting 'Disconnected' error after deploy with coreOS+fleet

### ISSUE THREAD

**Issue by maryiavarabyeva** [openstf/setup-examples#10]
Good day! I successfully deployed stf to cluster according to your instructions and was able to login. but on devices page I always getting error saying disconnected. My device (Android 6.0.1, Nexus 9) not available via stf UI. And after deploy it's not available on local via adb (adb devices return nothing). Before deployment it was ok.
Operation system OS X 10.11.4 
<img width="953" alt="screen shot 2016-04-06 at 4 22 26 pm" src="https://cloud.githubusercontent.com/assets/13525447/14318323/ef99903e-fc14-11e5-8973-11930155ca4a.png">

**Comment by tadesushilgithub** [comment]
@maryiavarabyeva On which os you deployed this?
