### ISSUE TITLE
I am getting error while running vagrant up

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/setup-examples#13]
I have installed VirtualBox on mac still why I am getting this error?

No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

**Comment by vbanthia-zz** [comment]
Well this is vagrant related problem and I never had this issue before so can't comment on it. I will suggest to post this issue on vagrant repo instead.
