### ISSUE TITLE
Doubt about cluster environment

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/setup-examples#14]
**Please clear my below mentioned doubt :**

I have scenario like Ubuntu-1 has 20 devices + Ubuntu-2 has 20 devices. Can Deployment guide helps us to bring **both 2 boxes under 1 url**, Where I can see total 40 devices after login?. I got success using Deployment guide help in setting up the STF in Mac OS but Failed in Ubuntu.

**Comment by vbanthia-zz** [comment]
Yes. It can. Read the whole example and deployment doc for clarification.
