### ISSUE TITLE
Example using stf-api unit.

### ISSUE THREAD

**Issue by jonatasteixeira-zz** [openstf/setup-examples#16]
Hello there. I suggest create another cluster structure to use as example, and include STF-API service in this one.

**Comment by vbanthia-zz** [comment]
Added stf-api unit here, https://github.com/openstf/setup-examples/commit/f059290451b5a568c33dbf97cf1ef6965e3d42c6

**Comment by jonatasteixeira-zz** [comment]
Hey Vishal,

Thanks for share!

Best []
