### ISSUE TITLE
Deploy openstf in kubernetes

### ISSUE THREAD

**Issue by dimasaryo** [openstf/setup-examples#17]
Hi guys,

Just in case someone are interested to deploy openstf in kubernetes. https://github.com/dimasaryo/stf-k8s

**Comment by sh0kunin** [comment]
how do you access the open stf in kubernetes?

**Comment by dimasaryo** [comment]
just use the internal/external ip of the stf-nginx service
`# kubectl get service stf-nginx`

**Comment by sh0kunin** [comment]
Where do you keep stf-processor service? on you local machine?, because there is no configuration for that?

**Comment by sh0kunin** [comment]
Also I don't get any external IP for nginx.
