### ISSUE TITLE
some fleets do not work

### ISSUE THREAD

**Issue by dyxrdyxr** [openstf/setup-examples#19]
I follow the setup-examples, but some fleets do not work
![2017-06-29 1 03 31](https://user-images.githubusercontent.com/27947461/27672310-82554bf2-5ccc-11e7-9dfe-9c7214f49328.png)
 
can you help me?

**Comment by vbanthia-zz** [comment]
services are activating. All these services need to download docker images which can take time that is why it will show like that for some time depending on your internet connection.

**Comment by dyxrdyxr** [comment]
but I wait for several hours and 
fleetctl unload stf-api@3700.service and fleetctl start stf-api@3700.service and then ssh to core-02

 journalctl -u stf-api@3700.service
![2017-06-30 8 55 17](https://user-images.githubusercontent.com/27947461/27716571-e64459fa-5d71-11e7-9a03-3c32a54f553b.png)

**Comment by vbanthia-zz** [comment]
You can see in the logs that some docker layers are not downloaded properly.There is some `Retry` going on. Check if you can download image or not. `docker pull openstf/stf`

**Comment by dyxrdyxr** [comment]
yes, you're right. I run "docker pull openstf/stf" manually 
![2017-06-30 9 05 22](https://user-images.githubusercontent.com/27947461/27716772-46ceb288-5d73-11e7-808b-a59ff988cf08.png)
and some docker layers are not downloaded completely.
so for each core I can run "docker pull openstf/stf" manually , and when stf is downloaded completely , then restart each inactive unit?

**Comment by dyxrdyxr** [comment]
now it works. I change another docker registry mirror.
thanks.
