### ISSUE TITLE
FleetCtl not working

### ISSUE THREAD

**Issue by ronakved** [openstf/setup-examples#21]
I'm following the given instructions by exporting the endpoint, then trying to list the machines with the fleetctl command. This is what I'm getting in the command line:

Unable to initialize client: failed initializing SSH client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain

Any help would be appreciated.

**Comment by sorccu** [comment]
Unfortunately fleet is pretty much dead. I would recommend trying to find another method to deploy the system. You can, for example, distribute the unit files yourself. The main downside is that the system won't heal if something goes down. Some people have had success with Kubernetes as well, but we don't have an official guide for that.
