### ISSUE TITLE
Why services can not be active?

### ISSUE THREAD

**Issue by 442895160** [openstf/setup-examples#4]
Hi,

When I try to start adbd and rethindkdb-proxy-28015 services, they are always in activating state even I've waiting for several hours. sometimes rethindkdb-proxy-28015 service can be active but adbd always can not. I am wondering if this is caused by my network issue, or by some special settings?

**$ fleetctl list-units**
UNIT                MACHINE             ACTIVE      SUB
adbd.service            24d030d4.../172.17.8.101    activating  start-pre
adbd.service            7975d30e.../172.17.8.103    activating  start-pre
adbd.service            998c246c.../172.17.8.102    activating  start-pre
rethinkdb-proxy-28015.service   24d030d4.../172.17.8.101    activating  start-pre
rethinkdb-proxy-28015.service   7975d30e.../172.17.8.103    activating  start-pre
rethinkdb-proxy-28015.service   **_998c246c.../172.17.8.102_**  activating  start-pre

**core@core-01 ~ $ journalctl --unit adbd**
-- Logs begin at Sun 2016-02-14 08:56:47 UTC, end at Mon 2016-02-15 01:04:30 UTC. --
Feb 14 09:01:09 core-01 systemd[1]: Starting ADB daemon...
Feb 14 09:01:20 core-01 docker[1522]: latest: Pulling from sorccu/adb
Feb 14 09:01:20 core-01 docker[1522]: bbe1c4256df3: Pulling fs layer
Feb 14 09:01:20 core-01 docker[1522]: 911d09728ffd: Pulling fs layer
Feb 14 09:01:20 core-01 docker[1522]: 615765bc0d9f: Pulling fs layer
Feb 14 09:01:20 core-01 docker[1522]: a3ed95caeb02: Pulling fs layer
Feb 14 09:01:20 core-01 docker[1522]: bd94165f831f: Pulling fs layer
Feb 14 09:01:20 core-01 docker[1522]: 8df1d3ccbdf7: Pulling fs layer
Feb 14 09:01:20 core-01 docker[1522]: 004956143d61: Pulling fs layer
Feb 14 09:01:20 core-01 docker[1522]: 5334fd0b4673: Pulling fs layer
Feb 14 09:01:20 core-01 docker[1522]: bbe1c4256df3: Waiting
Feb 14 09:01:20 core-01 docker[1522]: 911d09728ffd: Waiting
Feb 14 09:01:20 core-01 docker[1522]: 615765bc0d9f: Waiting
Feb 14 09:01:20 core-01 docker[1522]: a3ed95caeb02: Waiting
Feb 14 09:01:20 core-01 docker[1522]: bd94165f831f: Waiting
Feb 14 09:01:20 core-01 docker[1522]: 8df1d3ccbdf7: Waiting
Feb 14 09:01:20 core-01 docker[1522]: 004956143d61: Waiting
Feb 14 09:01:20 core-01 docker[1522]: 5334fd0b4673: Waiting
Feb 14 09:03:24 core-01 systemd[1]: adbd.service: Control process exited, code=exited status=2
Feb 14 09:03:24 core-01 systemd[1]: Stopped ADB daemon.
Feb 14 09:03:24 core-01 systemd[1]: adbd.service: Unit entered failed state.
Feb 14 09:03:24 core-01 systemd[1]: adbd.service: Failed with result 'exit-code'.
Feb 14 09:03:40 core-01 systemd[1]: Stopped ADB daemon.
Feb 14 09:04:45 core-01 systemd[1]: Starting ADB daemon...
Feb 14 09:04:45 core-01 docker[1648]: Failed to kill container (adbd): Error response from daemon: Cannot kill container adbd: No such container: adbd
Feb 14 09:04:45 core-01 docker[1654]: Failed to remove container (adbd): Error response from daemon: No such container: adbd
Feb 14 09:04:45 core-01 systemd[1]: Started ADB daemon.
Feb 14 09:04:45 core-01 docker[1671]: Unable to find image 'sorccu/adb:latest' locally
Feb 14 09:04:50 core-01 docker[1671]: latest: Pulling from sorccu/adb
Feb 14 09:04:50 core-01 docker[1671]: bbe1c4256df3: Pulling fs layer
Feb 14 09:04:50 core-01 docker[1671]: 911d09728ffd: Pulling fs layer
Feb 14 09:04:50 core-01 docker[1671]: 615765bc0d9f: Pulling fs layer
Feb 14 09:04:50 core-01 docker[1671]: a3ed95caeb02: Pulling fs layer
Feb 14 09:04:50 core-01 docker[1671]: bd94165f831f: Pulling fs layer
Feb 14 09:04:50 core-01 docker[1671]: 8df1d3ccbdf7: Pulling fs layer
Feb 14 09:04:50 core-01 docker[1671]: 004956143d61: Pulling fs layer
Feb 14 09:04:50 core-01 docker[1671]: 5334fd0b4673: Pulling fs layer
Feb 14 09:04:50 core-01 docker[1671]: bbe1c4256df3: Waiting
Feb 14 09:04:50 core-01 docker[1671]: 911d09728ffd: Waiting
Feb 14 09:04:50 core-01 docker[1671]: 615765bc0d9f: Waiting
Feb 14 09:04:50 core-01 docker[1671]: a3ed95caeb02: Waiting
Feb 14 09:04:50 core-01 docker[1671]: bd94165f831f: Waiting
Feb 14 09:04:50 core-01 docker[1671]: 8df1d3ccbdf7: Waiting
Feb 14 09:04:50 core-01 docker[1671]: 004956143d61: Waiting
Feb 14 09:04:50 core-01 docker[1671]: 5334fd0b4673: Waiting
Feb 14 09:07:30 core-01 docker[1671]: bbe1c4256df3: Retrying in 5 seconds
Feb 14 09:07:31 core-01 docker[1671]: bbe1c4256df3: Retrying in 4 seconds
Feb 14 09:07:32 core-01 docker[1671]: bbe1c4256df3: Retrying in 3 seconds
Feb 14 09:07:33 core-01 docker[1671]: bbe1c4256df3: Retrying in 2 seconds
Feb 14 09:07:34 core-01 docker[1671]: bbe1c4256df3: Retrying in 1 seconds
Feb 14 09:15:13 core-01 docker[1671]: bbe1c4256df3: Retrying in 10 seconds
Feb 14 09:15:14 core-01 docker[1671]: bbe1c4256df3: Retrying in 9 seconds
Feb 14 09:15:15 core-01 docker[1671]: bbe1c4256df3: Retrying in 8 seconds
Feb 14 09:15:16 core-01 docker[1671]: bbe1c4256df3: Retrying in 7 seconds
Feb 14 09:15:17 core-01 docker[1671]: bbe1c4256df3: Retrying in 6 seconds
Feb 14 09:15:18 core-01 docker[1671]: bbe1c4256df3: Retrying in 5 seconds
Feb 14 09:15:19 core-01 docker[1671]: bbe1c4256df3: Retrying in 4 seconds
Feb 14 09:15:20 core-01 docker[1671]: bbe1c4256df3: Retrying in 3 seconds
Feb 14 09:15:21 core-01 docker[1671]: bbe1c4256df3: Retrying in 2 seconds
Feb 14 09:15:22 core-01 docker[1671]: bbe1c4256df3: Retrying in 1 seconds
Feb 14 09:21:02 core-01 docker[1671]: bbe1c4256df3: Retrying in 15 seconds
Feb 14 09:21:03 core-01 docker[1671]: bbe1c4256df3: Retrying in 14 seconds
Feb 14 09:21:04 core-01 docker[1671]: bbe1c4256df3: Retrying in 13 seconds
Feb 14 09:21:05 core-01 docker[1671]: bbe1c4256df3: Retrying in 12 seconds
Feb 14 09:21:06 core-01 docker[1671]: bbe1c4256df3: Retrying in 11 seconds
Feb 14 09:21:07 core-01 docker[1671]: bbe1c4256df3: Retrying in 10 seconds
Feb 14 09:21:08 core-01 docker[1671]: bbe1c4256df3: Retrying in 9 seconds
Feb 14 09:21:09 core-01 docker[1671]: bbe1c4256df3: Retrying in 8 seconds
Feb 14 09:21:10 core-01 docker[1671]: bbe1c4256df3: Retrying in 7 seconds
Feb 14 09:21:11 core-01 docker[1671]: bbe1c4256df3: Retrying in 6 seconds
Feb 14 09:21:12 core-01 docker[1671]: bbe1c4256df3: Retrying in 5 seconds
Feb 14 09:21:13 core-01 docker[1671]: bbe1c4256df3: Retrying in 4 seconds
Feb 14 09:21:14 core-01 docker[1671]: bbe1c4256df3: Retrying in 3 seconds
Feb 14 09:21:15 core-01 docker[1671]: bbe1c4256df3: Retrying in 2 seconds
Feb 14 09:21:16 core-01 docker[1671]: bbe1c4256df3: Retrying in 1 seconds
Feb 14 09:26:56 core-01 docker[1671]: bbe1c4256df3: Retrying in 20 seconds
Feb 14 09:26:57 core-01 docker[1671]: bbe1c4256df3: Retrying in 19 seconds
Feb 14 09:26:58 core-01 docker[1671]: bbe1c4256df3: Retrying in 18 seconds
Feb 14 09:26:59 core-01 docker[1671]: bbe1c4256df3: Retrying in 17 seconds
Feb 14 09:27:00 core-01 docker[1671]: bbe1c4256df3: Retrying in 16 seconds
Feb 14 09:27:01 core-01 docker[1671]: bbe1c4256df3: Retrying in 15 seconds
Feb 14 09:27:02 core-01 docker[1671]: bbe1c4256df3: Retrying in 14 seconds
Feb 14 09:27:03 core-01 docker[1671]: bbe1c4256df3: Retrying in 13 seconds
Feb 14 09:27:04 core-01 docker[1671]: bbe1c4256df3: Retrying in 12 seconds
Feb 14 09:27:05 core-01 docker[1671]: bbe1c4256df3: Retrying in 11 seconds
Feb 14 09:27:06 core-01 docker[1671]: bbe1c4256df3: Retrying in 10 seconds
Feb 14 09:27:07 core-01 docker[1671]: bbe1c4256df3: Retrying in 9 seconds
Feb 14 09:27:08 core-01 docker[1671]: bbe1c4256df3: Retrying in 8 seconds
Feb 14 09:27:09 core-01 docker[1671]: bbe1c4256df3: Retrying in 7 seconds
Feb 14 09:27:10 core-01 docker[1671]: bbe1c4256df3: Retrying in 6 seconds
Feb 14 09:27:11 core-01 docker[1671]: bbe1c4256df3: Retrying in 5 seconds
Feb 14 09:27:12 core-01 docker[1671]: bbe1c4256df3: Retrying in 4 seconds
Feb 14 09:27:13 core-01 docker[1671]: bbe1c4256df3: Retrying in 3 seconds
Feb 14 09:27:14 core-01 docker[1671]: bbe1c4256df3: Retrying in 2 seconds
Feb 14 09:27:15 core-01 docker[1671]: bbe1c4256df3: Retrying in 1 seconds
Feb 14 09:28:24 core-01 docker[1671]: bbe1c4256df3: Verifying Checksum
Feb 14 09:28:24 core-01 docker[1671]: bbe1c4256df3: Download complete
Feb 14 09:28:31 core-01 docker[1671]: bbe1c4256df3: Pull complete
Feb 14 09:28:31 core-01 docker[1671]: bbe1c4256df3: Pull complete
Feb 14 09:30:51 core-01 systemd[1]: Stopping ADB daemon...
Feb 14 09:30:51 core-01 docker[1871]: Failed to stop container (adbd): Error response from daemon: No such container: adbd
Feb 14 09:30:51 core-01 systemd[1]: adbd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 09:30:51 core-01 systemd[1]: Stopped adbd.service.
Feb 14 09:30:51 core-01 systemd[1]: adbd.service: Unit entered failed state.
Feb 14 09:30:51 core-01 systemd[1]: adbd.service: Failed with result 'exit-code'.
Feb 14 09:50:04 core-01 systemd[1]: Starting ADB daemon...
Feb 14 09:50:19 core-01 docker[1995]: latest: Pulling from sorccu/adb
Feb 14 09:50:19 core-01 docker[1995]: bbe1c4256df3: Already exists
Feb 14 09:50:19 core-01 docker[1995]: 911d09728ffd: Pulling fs layer
Feb 14 09:50:19 core-01 docker[1995]: 615765bc0d9f: Pulling fs layer
Feb 14 09:50:19 core-01 docker[1995]: a3ed95caeb02: Pulling fs layer
Feb 14 09:50:19 core-01 docker[1995]: bd94165f831f: Pulling fs layer
Feb 14 09:50:19 core-01 docker[1995]: 8df1d3ccbdf7: Pulling fs layer
Feb 14 09:50:19 core-01 docker[1995]: 004956143d61: Pulling fs layer
Feb 14 09:50:19 core-01 docker[1995]: 5334fd0b4673: Pulling fs layer
Feb 14 09:50:19 core-01 docker[1995]: 615765bc0d9f: Waiting
Feb 14 09:50:19 core-01 docker[1995]: a3ed95caeb02: Waiting
Feb 14 09:50:19 core-01 docker[1995]: bd94165f831f: Waiting
Feb 14 09:50:19 core-01 docker[1995]: 8df1d3ccbdf7: Waiting
Feb 14 09:50:19 core-01 docker[1995]: 004956143d61: Waiting
Feb 14 09:50:19 core-01 docker[1995]: 5334fd0b4673:

**Comment by vbanthia-zz** [comment]
I can't help much for this issue, as I don't have this environment setup on my machine. All I can do is suggest you ways to debug this problem.
- You can confirm if it is network problem by running docker directly, like

```
vagrant ssh core-01
docker run --rm -ti --net container:adbd sorccu/adb adb devices
```

If it is showing any output then there is no network problem.
- You can try restarting adbd container by

```
fleetctl unload adbd
fleetctl start adbd
```

**Comment by 442895160** [comment]
Thanks for your help! It may be caused by my network. Now my environment looks good.
