### ISSUE TITLE
Nginx fleet not starting

### ISSUE THREAD

**Issue by jogjitu** [openstf/setup-examples#6]
I have followed the commands mentioned the examples. However I am not able to start. No error are shown however the unit job is stuck in activating start-pre status all along.

Screenshot attached
<img width="547" alt="screen shot 2016-03-03 at 8 59 47 pm" src="https://cloud.githubusercontent.com/assets/5314376/13499197/493cfbe6-e183-11e5-886c-c1ba3a92ee1f.png">

**Comment by vbanthia-zz** [comment]
Can you post nginx systemd error. Use below command to get logs 

Journalctl -u nginx

**Comment by jogjitu** [comment]
I checked proxy_pass couldn't find anything with no semicolor;
here are the logs

```
Mar 03 13:37:19 core-01 docker[2630]: Status: Downloaded newer image for nginx:1.7.10
Mar 03 13:37:20 core-01 docker[2701]: Failed to kill container (nginx): Error response from daemon: Cannot kill container nginx: No such container: nginx
Mar 03 13:37:20 core-01 systemd[1]: Started STF nginx public load balancer.
Mar 03 13:37:20 core-01 docker[2709]: Failed to remove container (nginx): Error response from daemon: No such container: nginx
Mar 03 13:37:20 core-01 docker[2715]: 2016/03/03 13:37:20 [emerg] 1#0: directive "proxy_pass" is not terminated by ";" in /etc/nginx/nginx.conf:69
Mar 03 13:37:20 core-01 docker[2715]: nginx: [emerg] directive "proxy_pass" is not terminated by ";" in /etc/nginx/nginx.conf:69
Mar 03 13:37:20 core-01 systemd[1]: nginx.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 13:37:21 core-01 docker[2728]: Failed to stop container (nginx): Error response from daemon: No such container: nginx
Mar 03 13:37:21 core-01 systemd[1]: nginx.service: Control process exited, code=exited status=1




```

**Comment by vbanthia-zz** [comment]
show your nginx.conf file

**Comment by jogjitu** [comment]
here it is 

```
events {
  worker_connections 1024;
}

http {
  keepalive_timeout   65;
  types_hash_max_size 2048;

  default_type        application/octet-stream;

  upstream stf_app {
    # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
    server 172.17.8.103:3100 max_fails=0;
  }

  upstream stf_auth {
    # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
    server 172.17.8.103:3200 max_fails=0;
  }

  upstream stf_storage_apk {
    # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
    server 172.17.8.102:3300 max_fails=0;
  }

  upstream stf_storage_image {
    # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
    server 172.17.8.102:3400 max_fails=0;
  }

  upstream stf_storage {
    # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
    server 172.17.8.102:3500 max_fails=0;
  }

  upstream stf_websocket {
    # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
    server 172.17.8.101:3600 max_fails=0;
  }

  types {
    application/javascript  js;
    image/gif               gif;
    image/jpeg              jpg;
    text/css                css;
    text/html               html;
  }

  map $http_upgrade $connection_upgrade {
    default  upgrade;
    ''       close;
  }
 server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  stf.mydomain.org;
    root         /dev/null;


    resolver 8.8.4.4 8.8.8.8 valid=300s;
    resolver_timeout 10s;

    location ~ "^/d/1/([^/]+)/(?<port>[0-9]{5})/$" {
      # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
      proxy_pass http://172.17.8.101:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ "^/d/2/([^/]+)/(?<port>[0-9]{5})/$" {
      # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
      proxy_pass http://172.17.8.102:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ "^/d/3/([^/]+)/(?<port>[0-9]{5})/$" {
      # PLEASE UPDATE IP ADDRESS WITH APPROPRIATE ONE
      proxy_pass http://172.17.8.103:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /s/image/ {
      proxy_pass http://stf_storage_image;
    }

    location /s/apk/ {
      proxy_pass http://stf_storage_apk;
    }

    location /s/ {
      client_max_body_size 1024m;
      client_body_buffer_size 128k;
      proxy_pass http://stf_storage;
    }

location /socket.io/ {
      proxy_pass http://stf_websocket;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }

    location /auth/ {
      proxy_pass http://stf_auth/auth/;
    }

    location / {
      proxy_pass http://stf_app;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }
  }
}
```

**Comment by sorccu** [comment]
I think it's complaining about https://github.com/openstf/setup-examples/blob/872dd8b02c4c234ebb56b8359a7b3eb35bbd4172/coreos/nginx.conf#L69, which means that your modified config isn't active.

**Comment by vbanthia-zz** [comment]
nginx.conf looks okay. Try restarting nginx service.

```
fleetctl unload nginx
fleetctl start nginx
```

In case if it doesn't work. Post error logs again.

**Comment by jogjitu** [comment]
Tried and it does not work. No error

Just says starting ngnix and never starts

Mar 03 17:13:23 core-01 docker[27365]: Status: Image is up to date for nginx:1.7.10
Mar 03 17:13:23 core-01 docker[27373]: Failed to kill container (nginx): Error response from daemon: Cannot kill container nginx: No such container: nginx
Mar 03 17:13:23 core-01 docker[27381]: Failed to remove container (nginx): Error response from daemon: No such container: nginx
Mar 03 17:13:23 core-01 systemd[1]: Started STF nginx public load balancer.
Mar 03 17:13:23 core-01 docker[27389]: 2016/03/03 17:13:23 [emerg] 1#0: directive "proxy_pass" is not terminated by ";" in /etc/nginx/nginx.conf:66
Mar 03 17:13:23 core-01 docker[27389]: nginx: [emerg] directive "proxy_pass" is not terminated by ";" in /etc/nginx/nginx.conf:66
Mar 03 17:13:23 core-01 systemd[1]: nginx.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 17:13:23 core-01 docker[27406]: Failed to stop container (nginx): Error response from daemon: No such container: nginx
Mar 03 17:13:23 core-01 systemd[1]: nginx.service: Control process exited, code=exited status=1
Mar 03 17:13:23 core-01 systemd[1]: nginx.service: Unit entered failed state.
Mar 03 17:13:23 core-01 systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 03 17:13:24 core-01 systemd[1]: nginx.service: Service hold-off time over, scheduling restart.
Mar 03 17:13:24 core-01 systemd[1]: Stopped STF nginx public load balancer.
Mar 03 17:13:24 core-01 systemd[1]: Starting STF nginx public load balancer...

**Comment by vbanthia-zz** [comment]
Did you change your nginx.conf file? Because previously error was at 69th line and now its at 66th.

Most probably you are making mistake in editing `nginx.conf` file. Try to fix the error in journalctl logs. It should work. I have never seen this problem before.
