### ISSUE TITLE
Android device is not showing in dashboard under device section

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/setup-examples#7]
I am done with setting up STF production environment and able to access on http://172.17.8.101 from browser but not able to see connected device under devices section. Please find below files, is there any thing i missed?
When I ran dab devices I'll get device listed.
Can I check log why device is not getting detect? How to check fleetctl logs and where it located? 

![vboxmanage_list_connecteddev](https://cloud.githubusercontent.com/assets/17309586/13984578/2cfce866-f11d-11e5-8763-507b8b11ec8f.png)
![vagrantfile](https://cloud.githubusercontent.com/assets/17309586/13984605/4f51eb64-f11d-11e5-9106-0b5478569968.png)
![runningservices](https://cloud.githubusercontent.com/assets/17309586/13984621/6ed26bbc-f11d-11e5-9b4b-8287c7422f65.png)
[nginx_conf.txt](https://github.com/openstf/setup-examples/files/185931/nginx_conf.txt)

**Comment by vbanthia-zz** [comment]
Check this https://github.com/openstf/setup-examples/issues/3

**Comment by tadesushilgithub** [comment]
I have referred the solution. It's working fine now :+1:
