### ISSUE TITLE
Getting fleetctl related error after restarting STF server

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/setup-examples#8]
Hi,

I have restarted running STF server and i did vagrant up for db and coreos but after running fleetctl start adbd rethinkdb-proxy-28015. "Error retrieving list of units from repository: Get http://domain-sock/fleet/v1/state?alt=json: dial unix /var/run/fleet.sock: connect: no such file or directory" and getting same error when running fleetctl list-units.

**Comment by vbanthia-zz** [comment]
Most probably you have not exported `FLEETCTL_ENDPOINT` environment variable. Export it as below and try running services again, I think it should work.

``` sh
export FLEETCTL_ENDPOINT=http://172.17.8.101:2379
```
