### ISSUE TITLE
Is it possible to set up openSTF server on one machine and have devices connected to another one? 

### ISSUE THREAD

**Issue by maryiavarabyeva** [openstf/setup-examples#9]
Thanks for the great tool! I have a question, is it possible to make Android devices available for stf server via adb by wifi for i.e.? or it's require to connect them to the same machine where server is running? Thanks much!

**Comment by sorccu** [comment]
This is covered by the DEPLOYMENT docs in the main repo. ADB over wifi is not recommended since the overhead of the ADB TCP protocol decreases performance by roughly 10x.
